<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net481;net8.0-windows7.0;net9.0-windows7.0</TargetFrameworks>
        <LangVersion>13</LangVersion>
        <Platforms>x64</Platforms>
        <UseWPF>true</UseWPF>
        
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="4.3.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='net481'">
        <Reference Include="PresentationCore" />
        <Reference Include="PresentationFramework" />
        <Reference Include="WindowsBase" />
        <Reference Include="System.Configuration" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\NUnit.ApplicationDomain\NUnit.ApplicationDomain.csproj" />
        <ProjectReference Include="..\NUnit.ApplicationDomain.Base.Test\NUnit.ApplicationDomain.Base.Test.csproj" />
    </ItemGroup>

</Project>
